### ISSUE TITLE
Screen becomes blank when window is resized by user.

### ISSUE THREAD

**Issue by LupusOssorum** [vladdeSV/scone#10]
When user resizes the `window` Scone behaves poorly.

Scone does not resize the internal `_cells` size and it also blacks out and will not redraw unless flush is called.

**Comment by vladdeSV** [comment]
have had problems with that. thanks for reminding me.

will look into this when i get the time to 👍

**Comment by vladdeSV** [comment]
i would like to say that you are correct in your explanation of what happens. iirc i had trouble with getting the resize event, and thus scone does not know when to redraw cells.

however, i do have some reasoning why resizing isn't supported: if a programmer decides to have a window of 80x20 cells and the user shrinks the window to 20x20, what should happen? (my reasoning was *just dont do that*)

however i see that it is something that a user might try to do. as mentioned, will look in to it when i have enough time :)

(why flush is needed is because according to scone's internal buffer, the cells haven't changed and shouldn't be redrawn. which is why flush is needed (but why it blacks out i cannot remember))

**Comment by vladdeSV** [comment]
opened a new issue #12

**Comment by vladdeSV** [comment]
issue #12 is closed, and so should this issue be. reopen if you encounter any problems
