### ISSUE TITLE
Multi-byte characters support

### ISSUE THREAD

**Issue by EmTee70** [vladdeSV/scone#27]
When trying to use "😃" as text it is displayed but the background gets broken.

Do you think you may solve this, it is for a small game inspired by old 8-Bit time programs...and only normal ascii is to limited...

**Comment by vladdeSV** [comment]
What happens is "😃" is multiple bytes, and so far I haven't looked into it.

It's just ASCII for now.

**Comment by vladdeSV** [comment]
This affects both Windows and POSIX

**Comment by vladdeSV** [comment]
*Leaving this as a reminder for myself once I tackle this in, presumably, two years*

The output is different on Windows and POSIX, and neither gives the expected output. Here's why:

## The problem
The emoji 😃 has a length of 4 (`"😃".length == 4`). In the code, when converting to a string, the emoji is split up into 4 different cells in the internal buffer.

In Windows, each cell is printed to the console separately, causing the following to appear as: ![windows console](https://i.imgur.com/mRC8GrA.png)

However, on POSIX it's different. Cells do not get printed separately. Instead they are all printed per line, meaning all cells' characters print together. **Uh oh**, because when the four characters are printed together, the terminal assumes it is an ordinary UTF-8 string, and rightfully so, displays the four characters as one character. This means 3 characters "get lost" in the process, causing this to happen: ![posix terminal](https://i.imgur.com/a2P8kmw.png)

## The solution
Enable support for UTF-8, *duh*. Problem is the Windows console (I think) only allows ASCII (and possibly extended ASCII). I currently do not know how to solve this for Windows.

POSIX is easier. If I could store the multi-byte characters in a `dchar` (maybe) the "characters getting lost" problem would be solved. Not 100% sure yet.

**P.S.** The reason why the title is set properly is because: the Windows code sets the title with an ASCII specific function, while POSIX sets it with an ordinary UTF-8 string

**Comment by vladdeSV** [comment]
The branch `utf-8` has a771251a15d7dfc68c58f85238d833e15a0d78c3, which stores characters as `dchar`s (UTF-32), which can store the emoji 😃, and print it out properly **on POSIX**

Still having trouble with Windows

**Comment by vladdeSV** [comment]
Closing this as the branch `v3` will have partial* support for multi-byte characters.

* partial support on Windows, "full" support on POSIX

**Comment by EmTee70** [comment]
Will there be multi-byte characters in the future for Linux/POSIX, too?

**Comment by vladdeSV** [comment]
Excuse me, I wrote that oddly. There will be multi-byte support on POSIX (and currently is on the branch `v3`)

**Comment by EmTee70** [comment]
Cool! I have to revisit your work for my little game. It uses some funny 'chars' as items in a maze based completely on chars in terminal.
